Repository nextcloud/logreader, pull requests merged in 2023-06, with the labels that each got.

#844 chore(CI): Adjust testing matrix for Nextcloud 26 on stable26
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm-matrix.yml
  composer.json
  composer.lock
Labels: 4. to release

#860 Audit and update dependencies [stable26]
  js/logreader-main.js
  js/logreader-main.js.map
  package-lock.json
Labels: dependencies

#885 Migrate more files to Typescript
  js/logreader-main.js
  js/logreader-main.js.map
  package-lock.json
  package.json
  src/Components/LogTable.js
  src/Components/Settings.js
  src/DateFormatConverter.ts
  src/LogFileParser.js
  src/LogFileParser.ts
  src/Providers/ClipboardProvider.js
  src/Providers/ClipboardProvider.ts
  src/Providers/LogFile.ts
  src/Providers/LogProvider.js
  src/Providers/LogProvider.ts
  src/Search.js
  src/Search.ts
Labels: enhancement, 3. to review

#861 Audit and update dependencies [stable25]
  js/logreader-main.js
  js/logreader-main.js.map
  package-lock.json
Labels: dependencies

#862 Audit and update dependencies [stable24]
  js/logreader-main.js
  js/logreader-main.js.map
  package-lock.json
  package.json
Labels: 2. developing, dependencies

#798 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#796 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#884 fix(a11y): `Copy` menu entries should be implemented as buttons
  js/logreader-main.css
  js/logreader-main.css.map
  js/logreader-main.js
  js/logreader-main.js.map
  src/Components/LogTable.css
  src/Components/LogTable.js
Labels: backport-request, 3. to review

#915 chore: update node engines to next LTS
  package.json
Labels: 3. to review, dependencies, automated

#887 Make log levels button keyboard focusable and activable
  js/logreader-main.css
  js/logreader-main.css.map
  js/logreader-main.js
  js/logreader-main.js.map
  src/Components/LogTable.css
  src/Components/LogTable.js
Labels: accessibility
