Repository nextcloud/logreader, pull requests merged in 2023-07, with the labels that each got.

#924 chore[stable27] - audit dependencies
  package-lock.json
Labels: 3. to review, security, dependencies, javascript

#925 chore[stable26] - audit dependencies
  js/logreader-main.js.map
  package-lock.json
Labels: 3. to review, security, dependencies, javascript

#913 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#937 chore(deps) - bump semver to 6.3.1
  package-lock.json
Labels: security, dependencies, javascript

#944 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#943 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#903 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#950 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#949 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
