Repository nextcloud/logreader, pull requests merged in 2023-11, with the labels that each got.

#1034 Update to psalm 5 to match what server is using
  composer.json
  composer.lock
  lib/Listener/LogListener.php
  lib/Log/LogIterator.php
  lib/Log/SearchFilter.php
  psalm.xml
Labels: 3. to review

#1021 Add a setupcheck for errors and warnings in log file
  lib/AppInfo/Application.php
  lib/SetupChecks/LogErrors.php
  tests/Unit/SetupChecks/LogErrorsTest.php
Labels: enhancement, 3. to review

#1019 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#1036 Update workflows and only run required ones
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm-matrix.yml
  composer.json
  composer.lock
Labels: 3. to review

#1043 [stable26] Fix styles location to they can be loaded
  css/logreader-main.css
  css/logreader-main.css.map
  js/logreader-main.css.map
  templates/index.php
  webpack/prod.config.js
Labels: bug, 3. to review, regression

#1042 [stable27] Fix styles location to they can be loaded
  css/logreader-main.css
  css/logreader-main.css.map
  js/logreader-main.css.map
  templates/index.php
  webpack/prod.config.js
Labels: bug, 3. to review, regression

#1045 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#998 [26] allow printing log messages during occ
  .github/workflows/psalm-matrix.yml
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Listener/LogListener.php
  lib/Log/Console.php
  tests/stubs/stub.phpstub
Labels: 3. to review

#1052 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1044 fix(ci): Run tests also on schedule on master so we can get code coverage
  .github/workflows/node-test.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  codecov.yml
Labels: 3. to review

#1060 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1027 Feature: set log level via settings UI
  css/logreader-main.css
  js/Splitter-7c596d5a.mjs
  js/Splitter-7c596d5a.mjs.map
  js/Splitter-9140b094.mjs
  js/Splitter-9140b094.mjs.map
  js/logreader-main.mjs
  lib/Constants.php
  lib/Controller/SettingsController.php
  lib/Service/SettingsService.php
  package-lock.json
  src/components/settings/AppSettingsDialog.vue
  src/components/settings/SettingsSetLogLevel.vue
  src/interfaces/IAppSettings.ts
  src/store/settings.ts
  tests/Unit/Controller/SettingsControllerTest.php
  tests/Unit/Service/SettingsServiceTest.php
Labels: enhancement, 2. developing, feedback-requested
