Repository nextcloud/logreader, pull requests merged in 2023-12, with the labels that each got.

#1069 Lower setup check level from error/warning to warning/info
  lib/SetupChecks/LogErrors.php
  tests/Unit/SetupChecks/LogErrorsTest.php
Labels: backport-request, 3. to review

#1067 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1061 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#1075 fix: Allow older app values to be set
  lib/Service/SettingsService.php
Labels: bug, backport-request, 3. to review

#1083 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
