Repository nextcloud/logreader, pull requests merged in 2024-03, with the labels that each got.

#1156 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies

#1149 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1168 [stable28] Build(deps): bump vite from 4.5.0 to 4.5.2, audit dependencies
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#1145 [stable28] chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#1144 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#1179 perf: read larger chunks in logiterator
  lib/Log/LogIterator.php
Labels: 3. to review

#1169 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#1177 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1175 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1195 fix: Catch exception from LogIteratorFactory, throw a clean error when log_type is not file
  lib/Log/LogIteratorFactory.php
  lib/SetupChecks/LogErrors.php
Labels: backport-request, 3. to review
