Repository nextcloud/logreader, pull requests merged in 2024-01, with the labels that each got.

#1106 [stable27] chore: audit dependencies
  package-lock.json
Labels: 3. to review, dependencies, javascript

#1108 [stable26] chore: audit dependencies
  package-lock.json
Labels: 3. to review, dependencies, javascript

#1107 [stable28] chore: audit dependencies
  package-lock.json
Labels: 3. to review, dependencies, javascript

#1090 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#1089 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#1105 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1116 Update npm and node engines versions
  package.json
Labels: dependencies

#1115 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1114 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1091 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated, feedback-requested
