Repository nextcloud/logreader, pull requests merged in 2024-12, with the labels that each got.

#1433 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1424 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1449 fix(LogErrors): Handle unsupported log_type gracefully
  lib/Exception/UnsupportedLogTypeException.php
  lib/Log/LogIteratorFactory.php
  lib/SetupChecks/LogErrors.php
Labels: bug, backport-request, 3. to review

#1445 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1443 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1455 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
