Repository nextcloud/logreader, pull requests merged in 2024-06, with the labels that each got.

#1251 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1270 chore(CI): Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies

#1286 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1281 fix(deps): Bump dependencies to match nextcloud/ocp:dev-stable27
  .php-cs-fixer.dist.php
  composer.json
  composer.lock
  lib/Controller/LogController.php
  psalm.xml
Labels: 3. to review

#1252 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1253 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1292 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
