Repository nextcloud/logreader, pull requests merged in 2025-03, with the labels that each got.

#1535 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1545 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1546 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1532 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1547 [master] Fix npm audit
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#1538 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1537 [stable31] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1536 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1553 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1554 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1556 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1555 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1562 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1567 chore: update ci workflows
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, technical debt

#1569 [stable30] chore: update CI workflows
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, technical debt

#1564 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1574 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1573 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1575 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1577 fix: Do not register listener when not in console
  lib/AppInfo/Application.php
  lib/Listener/LogListener.php
Labels: bug, 3. to review, php

#1582 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1583 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1584 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1587 [stable31] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1585 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1586 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
